### ISSUE TITLE
I lost ALL DCS Effect Settings

### ISSUE THREAD

**Issue by cristianghetau** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#13]
SSA crashed and I lost all my DCS Effect Settings. I tried to Import it from the SettingsDatabase.bin file but to no avail. Only the Generic Profiles are shown.

**Comment by f4l0** [comment]
SSA saves the settings while closing or explicit user export. So maybe you got bad luck. I hope that you were able to recover your beloved settings somehow...
