### ISSUE TITLE
 No engine beat in DCS.

### ISSUE THREAD

**Issue by Willoughby888** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#15]
This has running this for a while with 109 in DCS but in last few days the engine beat and one or two other ‘events’ aren’t working even when turned up in Aviator settings. I’m getting some effects, like runway rumble, g effects and crash impacts. The tests work fine in Sound and Aviator settings panels and engine beat and other missing effects appear (sent/play) in the ‘event’ log but nothing is being transmitted to the pads.

The issue is the same with DCs MT and open beta versions and was working perfectly with both until recently. 

I’ve already tried uninstall/install of sound and Aviator modules x 2, repair DCS, checked cables and Aviator output settings. I’ve also installed bets versions of both sound module and Aviator and still not working.

Windows 10
DCS Open beta 2.8.7.42718
Simshaker Avitors 2.6 
Sound Module lasted stable

**Comment by f4l0** [comment]
Thx, I'll have a look

**Comment by f4l0** [comment]
I just tested it on my side. I see the engine effect triggered in SSA. Which pad do you use?
