### ISSUE TITLE
UDP port in use crash

### ISSUE THREAD

**Issue by sushiat** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#20]
**Describe the bug**
When starting the application the Xplane module tries to create a UDP listen port, when that port is in use by some other application the whole app crashes. There is no exception handling in place, nor an error message of any kind. I'm only using it for MSFS only but am still affected by this randomly (not often but annoying as you have to reboot the entire computer to fix it).

Error message shows the chain starting in the mainform constructor, to the core dataprovider

**To Reproduce**
Have the port in use and start simshaker

**Expected behavior**
Ideally the application would start normal and just disable the xplane module when the port is blocked, allowing normal use for other sims. And show an error dialog about that fact for the xplane users. But add error handling for the case that a UDP port is blocked instead of crash.

**Screenshots**
![image](https://github.com/SimShaker-for-Aviators/SimShaker-for-Aviators-Releases/assets/6118673/809759fd-b260-4b27-b8f6-02091aa31ff3)

**System (please complete the following information):**
 - Windows version: Win11
 - Simulator version: MFS2020
 - SSA version: 2.7.0

**Additional context**

**Comment by f4l0** [comment]
Thanks for your report. I'll have a look and see what I can do here...

**Comment by witcohe** [comment]
I am having the same issue with v2.7.0 and 2.7.3.

**Comment by f4l0** [comment]
I reworked the exception. Please check the next beta release...

**Comment by SnapRoll1** [comment]
![ssa](https://github.com/SimShaker-for-Aviators/SimShaker-for-Aviators-Releases/assets/165329815/83cab179-f6e7-4edf-8ef7-8c38f3058af0)

I got there errors once I stopped DCS.

**Comment by f4l0** [comment]
New beta incomming ;)

**Comment by f4l0** [comment]
@SnapRoll1 any feedback?
