### ISSUE TITLE
DCS Spitfire no engine beat

### ISSUE THREAD

**Issue by lluisYasT** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#21]
There is no engine beat on the Spitfire in DCS.
I have enabled the logs and there are no messages mentioning it when flying, bat every other effect seems to be working. Other WWII aircraft (P-47D or Mosquito for example) work ok and I can see the piston beat messages in the log.

**Comment by f4l0** [comment]
Did you test the latest beta? I reworked the engine effect for the Spitfire...

**Comment by lluisYasT** [comment]
It looks like it wasn't installed correctly. After downloading 2.7.2 again and repairing the installation, it is working again.

Thanks!
