### ISSUE TITLE
DCS aircraft no more detected

### ISSUE THREAD

**Issue by Jiphou** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#24]
**Describe the bug**
After installing Quest3 and Janjan vocal DCS command, SSA activates shakers but Aircraft are no more detected by SSA
Windows stays on A10A, if another aircraft is selected like M2000 and parameters modified they are not used

**To Reproduce**
1. Go to DCS
2. Click on Replay any flight

**Expected behavior**
With my G2, I had sound of DCS in the HMD, this is ok with Q3 but the aircraft of the flight was automatically detected and the relative SSA file used

**Screenshots**
NA

**System (please complete the following information):**
 - Windows version: [Win10] 22H2 build 19045.4291
 - Simulator version: [DCS OpenBeta 2.9.4.53707]
 - SSA version: [SSA 2.7] sound module 2.36

**Additional context**
simshaker.lua script line 404 was modified in:  local li = parse_indicationSS(5) to allow use of Janjan vocal software

**Comment by f4l0** [comment]
First idea would be to check your export.lua.
Maybe the modification you did is not correct. Do you get any SSA/DCS errors?

**Comment by Jiphou** [comment]
﻿Hi and thank you for your answerI made a survey of the export.lua with notepad++ and blanked added lines used by other software.This made the SSA and sound module working wellThen I identified a conflict with the line of my vocal command software from janjan that blocked SSA so I moved the janjan line on the top of the export and SSA looks like working well for now….I joined my export.lua fileI’ve not yet checked if this has an impact on the vocal software working.Thanks a lot for giving me a cue to the solution.Le 16 avr. 2024 à 07:36, f4l0 ***@***.***> a écrit :﻿
First idea would be to check your export.lua.
Maybe the modification you did is not correct. Do you get any SSA/DCS errors?
