### ISSUE TITLE
CH-47 Rotors have no effect on HF8 Motion Pad

### ISSUE THREAD

**Issue by Mantikor83** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#25]
Hi,
first of all, thanks a lot for your great work! =)

I have tested the latest Beta Version with the introduced CH-47 Setup. With my HF8 Motion Pad it seems, that the Main Rotor High/Low Settings have no efect. While there is a clear feedback from turbulences, vortex etc. the rotors creates no vibration, neither during startup or during flight on full levers.

I have completly uninstalled simshaker and re installed it to ensure, that it is not a local config bug, but I face the same issue. Maybe it's some attention worth and can be fixed. =)

BR

**Comment by f4l0** [comment]
Hey, thanks for reporting. However, I don't own a HF8 pad. Thus I can not reproduce it on my side... The CH-47F uses the same effect files an logic as other helos. Did you test others?

**Comment by Mantikor83** [comment]
Yeah, I use it also for the AH64, the OH58 and the UH60 Mod (to be honest it's the MI8 in this Case :D), everything is working fine. 

Can I support you in any way with testing on the HF8? I'm a studied software developer, so if you introduce me a litte what I can/shall do, I expect, that I could make adjustments to lua files and check if things are getting better or not. =)

**Comment by f4l0** [comment]
Check if the DCS Debug window in SSA shows RPM values... There will be a new release soon, I tweaked the thresholds for the CH-47F

**Comment by Mantikor83** [comment]
I fixed it... don't know why, but my HF8 was the issue, reinstall it fixed the problem! Thanks for your attention and support =) now it is working as expected. =)
