### ISSUE TITLE
SimShaker for aviators strange issue

### ISSUE THREAD

**Issue by mibo46** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#9]
Hi,
Have downloaded SimShaker for aviators and when I open the shortcut it created, nothing happens just a !/2 second blink on the desktop. Is this normal?  It does not open a page with settings or anything else.
Please advise. THANKS

**Comment by f4l0** [comment]
Did you check your taskbar? SSA usually adds an icon there which you can click to start SSA...

**Comment by mibo46** [comment]
Thanks for you reply but there is no icon on my taskbar. When I click on the shortcut it blinks less than a second on my desktop and nothing happens.





On Monday, March 27, 2023 at 01:43:19 AM AST, f4l0 ***@***.***> wrote: 







Did you check your taskbar? SSA usually adds an icon there which you can click to start SSA...

**Comment by f4l0** [comment]
Looks like SSA crashes, could you please check the logs of SSA in the installation folder?

**Comment by mibo46** [comment]
Thank you, here attached my log file. I think I have to uninstall everything and reinstall it?
Also my SimShaker Sound module is not making any vibration. It shows the green bars but no sound.
Have not used the Sinshaker sound module and SimShaker for aviators for a long time. As I have reinstalled windows 10 maybe I have to regenerate the key from Andre's shop for the Gametrix JetSeat. Have asked Andres but he referred me to https://forum.dcs.world/topic/147495-official-simshaker-for-aviators/ . And did not say anything about reactivating the Key.
I have also the buttkicker and this works.




On Tuesday, March 28, 2023 at 12:24:18 PM AST, f4l0 ***@***.***> wrote: 







Looks like SSA crashes, could you please check the logs of SSA in the installation folder? Also my

**Comment by f4l0** [comment]
Please attach the logfile in the github issue. It was not attached to your mail...

**Comment by mibo46** [comment]
Thanks for your help. 
I could find the SimShaker Menu on the taskbar. I tried to open Simshaker for Aviators and SimShaker Sound module. Tried it with DCS and without. It does not register sound and in the Module you can see the green bars when Testing but no sound. Please find attached Sim Shaker Sound Module and INSTALLSTATE FILE,cannot see a Log file in  Andre>ProgramFiles(x86)>SimShaker Sound Module





On Friday, March 31, 2023 at 01:38:56 AM AST, f4l0 ***@***.***> wrote: 







Please attach the logfile in the github issue. It was not attached to your mail...

**Comment by mibo46** [comment]
Sorry forgot attachment-





On Friday, March 31, 2023 at 03:09:11 PM AST, Michel Bolli ***@***.***> wrote: 





Thanks for your help. 
I could find the SimShaker Menu on the taskbar. I tried to open Simshaker for Aviators and SimShaker Sound module. Tried it with DCS and without. It does not register sound and in the Module you can see the green bars when Testing but no sound. Please find attached Sim Shaker Sound Module and INSTALLSTATE FILE,cannot see a Log file in  Andre>ProgramFiles(x86)>SimShaker Sound Module





On Friday, March 31, 2023 at 01:38:56 AM AST, f4l0 ***@***.***> wrote: 







Please attach the logfile in the github issue. It was not attached to your mail...

**Comment by f4l0** [comment]
When you answer via mail, the attachments gets deleted thus I can not see...
I'm not the dev of the Sound Module. You may also visit our discord community!

**Comment by mibo46** [comment]
I changed the attachments with Paint, so it should come trough
![SimShaker Sound Module and log](https://user-images.githubusercontent.com/98842252/229303627-7f3e62c0-6ba6-4d82-a0be-a47ed52a797c.png)
![SimShaker Sound Module and log](https://user-images.githubusercontent.com/98842252/229303684-9843ba40-aff6-4f48-ab47-c095f1ad37e8.png)
!

**Comment by f4l0** [comment]
As I already told you, I'm not the dev for the soundmodule. Contact Andre or come to the discord and ask our question their...
